title: Kollektive Geographie Heidelberg
email: kollektive-geographie-heidelberg@posteo.de
url: "http://kollektive-geographie-heidelberg.de"
github_username: kollektive-geographie-heidelberg
remote_theme: poole/hyde
